#!/bin/bash
rm -rf  vendor/dolby/ds/apps/ds1/res/values-pt-rBR
rm -rf  vendor/dolby/Ds1UI/res/values-pt-rBR
rm -rf  vendor/mediatek/proprietary/frameworks/base/res/res/values-pt-rBR
rm -rf  vendor/mediatek/proprietary/packages/apps/Browser/res/values-pt-rBR
rm -rf  frameworks/support/v17/leanback/res/values-pt-rBR
rm -rf  frameworks/support/v7/mediarouter/res/values-pt-rBR
rm -rf  frameworks/support/v7/appcompat/res/values-pt-rBR
rm -rf  frameworks/opt/chips/res/values-pt-rBR
rm -rf  frameworks/opt/chips/sample/res/values-pt-rBR
rm -rf  frameworks/opt/setupwizard/library/main/res/values-pt-rBR
rm -rf  frameworks/opt/setupwizard/navigationbar/res/values-pt-rBR
rm -rf  frameworks/opt/photoviewer/res/values-pt-rBR
rm -rf  frameworks/opt/photoviewer/sample/res/values-pt-rBR
rm -rf  frameworks/base/core/res/res/values-pt-rBR
rm -rf  frameworks/base/packages/SettingsProvider/res/values-pt-rBR
rm -rf  frameworks/base/packages/VpnDialogs/res/values-pt-rBR
rm -rf  frameworks/base/packages/ExternalStorageProvider/res/values-pt-rBR
rm -rf  frameworks/base/packages/SystemUI/res/values-pt-rBR
rm -rf  frameworks/base/packages/DocumentsUI/res/values-pt-rBR
rm -rf  frameworks/base/packages/PrintSpooler/res/values-pt-rBR
rm -rf  frameworks/base/packages/SettingsLib/res/values-pt-rBR
rm -rf  frameworks/base/packages/CaptivePortalLogin/res/values-pt-rBR
rm -rf  frameworks/base/packages/Keyguard/res/values-pt-rBR
rm -rf  frameworks/base/packages/DefaultContainerService/res/values-pt-rBR
rm -rf  frameworks/base/packages/InputDevices/res/values-pt-rBR
rm -rf  frameworks/base/packages/Shell/res/values-pt-rBR
rm -rf  frameworks/base/packages/BackupRestoreConfirmation/res/values-pt-rBR
rm -rf  frameworks/base/packages/FusedLocation/res/values-pt-rBR
rm -rf  packages/apps/Contacts/res/values-pt-rBR
rm -rf  packages/apps/Settings/tests/app/res/values-pt-rBR
rm -rf  packages/apps/Settings/res/values-pt-rBR
rm -rf  packages/apps/Dialer/InCallUI/res/values-pt-rBR
rm -rf  packages/apps/Dialer/res/values-pt-rBR
rm -rf  packages/apps/PackageInstaller/res/values-pt-rBR
rm -rf  packages/apps/ManagedProvisioning/res/values-pt-rBR
rm -rf  packages/apps/CertInstaller/res/values-pt-rBR
rm -rf  packages/apps/TvSettings/Settings/res/values-pt-rBR
rm -rf  packages/apps/KeyChain/res/values-pt-rBR
rm -rf  packages/apps/ContactsCommon/res/values-pt-rBR
rm -rf  packages/screensavers/PhotoTable/res/values-pt-rBR
rm -rf  packages/screensavers/Basic/res/values-pt-rBR
rm -rf  packages/providers/ContactsProvider/res/values-pt-rBR
rm -rf  packages/providers/MediaProvider/res/values-pt-rBR
# rm values-fr-rCA
rm -rf ./vendor/mediatek/proprietary/packages/apps/HotKnotConnectivity/res/values-fr-rCA
rm -rf ./vendor/mediatek/proprietary/packages/apps/Calendar/res/values-fr-rCA
rm -rf ./vendor/mediatek/proprietary/packages/apps/FMRadio/res/values-fr-rCA
rm -rf ./vendor/mediatek/proprietary/packages/apps/HotKnotBeam/res/values-fr-rCA
rm -rf ./vendor/mediatek/proprietary/packages/apps/Exchange/res/values-fr-rCA
rm -rf ./vendor/mediatek/proprietary/packages/apps/Mms/res/values-fr-rCA
rm -rf ./frameworks/opt/chips/res/values-fr-rCA
rm -rf ./frameworks/opt/chips/sample/res/values-fr-rCA
rm -rf ./frameworks/opt/colorpicker/res/values-fr-rCA
rm -rf ./frameworks/opt/timezonepicker/res/values-fr-rCA
rm -rf ./frameworks/opt/setupwizard/library/main/res/values-fr-rCA
rm -rf ./frameworks/opt/setupwizard/navigationbar/res/values-fr-rCA
rm -rf ./frameworks/opt/datetimepicker/res/values-fr-rCA
rm -rf ./frameworks/opt/photoviewer/res/values-fr-rCA
rm -rf ./frameworks/opt/photoviewer/sample/res/values-fr-rCA
rm -rf ./frameworks/base/tests/Split/res/values-fr-rCA
rm -rf ./frameworks/base/packages/SettingsProvider/res/values-fr-rCA
rm -rf ./frameworks/base/packages/ExtShared/res/values-fr-rCA
rm -rf ./frameworks/base/packages/ExtServices/res/values-fr-rCA
rm -rf ./frameworks/base/packages/VpnDialogs/res/values-fr-rCA
rm -rf ./frameworks/base/packages/ExternalStorageProvider/res/values-fr-rCA
rm -rf ./frameworks/base/packages/SystemUI/res/values-fr-rCA
rm -rf ./frameworks/base/packages/WallpaperCropper/res/values-fr-rCA
rm -rf ./frameworks/base/packages/DocumentsUI/res/values-fr-rCA
rm -rf ./frameworks/base/packages/PrintSpooler/res/values-fr-rCA
rm -rf ./frameworks/base/packages/StatementService/res/values-fr-rCA
rm -rf ./frameworks/base/packages/PrintRecommendationService/res/values-fr-rCA
rm -rf ./frameworks/base/packages/SettingsLib/res/values-fr-rCA
rm -rf ./frameworks/base/packages/CaptivePortalLogin/res/values-fr-rCA
rm -rf ./frameworks/base/packages/Keyguard/res/values-fr-rCA
rm -rf ./frameworks/base/packages/DefaultContainerService/res/values-fr-rCA
rm -rf ./frameworks/base/packages/InputDevices/res/values-fr-rCA
rm -rf ./frameworks/base/packages/Shell/res/values-fr-rCA
rm -rf ./frameworks/base/packages/BackupRestoreConfirmation/res/values-fr-rCA
rm -rf ./frameworks/base/packages/FusedLocation/res/values-fr-rCA
rm -rf ./frameworks/base/packages/MtpDocumentsProvider/res/values-fr-rCA
rm -rf ./frameworks/ex/chips/res/values-fr-rCA
rm -rf ./packages/apps/Contacts/res/values-fr-rCA
rm -rf ./packages/apps/DeskClock/res/values-fr-rCA
rm -rf ./packages/apps/Music/res/values-fr-rCA
rm -rf ./packages/apps/Settings/tests/app/res/values-fr-rCA
rm -rf ./packages/apps/Settings/res/values-fr-rCA
rm -rf ./packages/apps/WallpaperPicker/res/values-fr-rCA
rm -rf ./packages/apps/Gallery2/res/values-fr-rCA
rm -rf ./packages/apps/BasicSmsReceiver/res/values-fr-rCA
rm -rf ./packages/apps/Dialer/InCallUI/res/values-fr-rCA
rm -rf ./packages/apps/Dialer/res/values-fr-rCA
rm -rf ./packages/apps/SpareParts/res/values-fr-rCA
rm -rf ./packages/apps/ExactCalculator/res/values-fr-rCA
rm -rf ./packages/apps/DevCamera/res/values-fr-rCA
rm -rf ./packages/apps/EmergencyInfo/res/values-fr-rCA
rm -rf ./packages/apps/PackageInstaller/res/values-fr-rCA
rm -rf ./packages/apps/Calendar/res/values-fr-rCA
rm -rf ./packages/apps/Bluetooth/res/values-fr-rCA
rm -rf ./packages/apps/Messaging/res/values-fr-rCA
rm -rf ./packages/apps/Nfc/res/values-fr-rCA
rm -rf ./packages/apps/HTMLViewer/res/values-fr-rCA
rm -rf ./packages/apps/Launcher2/res/values-fr-rCA
rm -rf ./packages/apps/SpeechRecorder/res/values-fr-rCA
rm -rf ./packages/apps/CellBroadcastReceiver/tests/res/values-fr-rCA
rm -rf ./packages/apps/CellBroadcastReceiver/res/values-fr-rCA
rm -rf ./packages/apps/PhoneCommon/res/values-fr-rCA
rm -rf ./packages/apps/Launcher3/WallpaperPicker/res/values-fr-rCA
rm -rf ./packages/apps/Launcher3/res/values-fr-rCA
rm -rf ./packages/apps/SoundRecorder/res/values-fr-rCA
rm -rf ./packages/apps/MusicFX/res/values-fr-rCA
rm -rf ./packages/apps/Camera2/res/values-fr-rCA
rm -rf ./packages/apps/Calculator/res/values-fr-rCA
rm -rf ./packages/apps/ManagedProvisioning/res/values-fr-rCA
rm -rf ./packages/apps/CertInstaller/res/values-fr-rCA
rm -rf ./packages/apps/TvSettings/Settings/res/values-fr-rCA
rm -rf ./packages/apps/Email/res/values-fr-rCA
rm -rf ./packages/apps/Email/UnifiedEmail/res/values-fr-rCA
rm -rf ./packages/apps/KeyChain/res/values-fr-rCA
rm -rf ./packages/apps/Stk/res/values-fr-rCA
rm -rf ./packages/apps/Tag/res/values-fr-rCA
rm -rf ./packages/apps/LegacyCamera/res/values-fr-rCA
rm -rf ./packages/apps/Protips/res/values-fr-rCA
rm -rf ./packages/apps/Gallery/res/values-fr-rCA
rm -rf ./packages/apps/Terminal/res/values-fr-rCA
rm -rf ./packages/apps/QuickSearchBox/res/values-fr-rCA
rm -rf ./packages/inputmethods/LatinIME/java/res/values-fr-rCA
rm -rf ./packages/inputmethods/OpenWnn/res/values-fr-rCA
rm -rf ./packages/services/Telecomm/res/values-fr-rCA
rm -rf ./packages/services/Telecomm/res_ext/values-fr-rCA
rm -rf ./packages/services/Telephony/res/values-fr-rCA
rm -rf ./packages/services/Telephony/sip/res/values-fr-rCA
rm -rf ./packages/screensavers/PhotoTable/res/values-fr-rCA
rm -rf ./packages/screensavers/Basic/res/values-fr-rCA
rm -rf ./packages/wallpapers/LivePicker/res/values-fr-rCA
rm -rf ./packages/providers/BookmarkProvider/res/values-fr-rCA
rm -rf ./packages/providers/ContactsProvider/res/values-fr-rCA
rm -rf ./packages/providers/CallLogProvider/res/values-fr-rCA
rm -rf ./packages/providers/MediaProvider/res/values-fr-rCA
rm -rf ./packages/providers/UserDictionaryProvider/res/values-fr-rCA
rm -rf ./packages/providers/TelephonyProvider/res/values-fr-rCA
rm -rf ./packages/providers/BlockedNumberProvider/res/values-fr-rCA
rm -rf ./packages/providers/TvProvider/res/values-fr-rCA
rm -rf ./packages/providers/DownloadProvider/res/values-fr-rCA
rm -rf ./packages/providers/DownloadProvider/ui/res/values-fr-rCA
rm -rf ./packages/providers/ApplicationsProvider/res/values-fr-rCA
rm -rf ./packages/providers/CalendarProvider/res/values-fr-rCA
# rm values-en-rAU
rm -rf ./vendor/mediatek/proprietary/packages/apps/Browser/res/values-en-rAU
rm -rf ./vendor/mediatek/proprietary/packages/apps/FMRadio/res/values-en-rAU
rm -rf ./vendor/mediatek/proprietary/packages/apps/Exchange/res/values-en-rAU
rm -rf ./vendor/mediatek/proprietary/packages/apps/QuickSearchBox/res/values-en-rAU
rm -rf ./frameworks/opt/chips/res/values-en-rAU
rm -rf ./frameworks/opt/chips/sample/res/values-en-rAU
rm -rf ./frameworks/opt/colorpicker/res/values-en-rAU
rm -rf ./frameworks/opt/timezonepicker/res/values-en-rAU
rm -rf ./frameworks/opt/setupwizard/library/main/res/values-en-rAU
rm -rf ./frameworks/opt/datetimepicker/res/values-en-rAU
rm -rf ./frameworks/opt/photoviewer/res/values-en-rAU
rm -rf ./frameworks/opt/photoviewer/sample/res/values-en-rAU
rm -rf ./frameworks/base/core/res/res/values-en-rAU
rm -rf ./frameworks/base/packages/SettingsProvider/res/values-en-rAU
rm -rf ./frameworks/base/packages/VpnDialogs/res/values-en-rAU
rm -rf ./frameworks/base/packages/ExternalStorageProvider/res/values-en-rAU
rm -rf ./frameworks/base/packages/SystemUI/res/values-en-rAU
rm -rf ./frameworks/base/packages/DocumentsUI/res/values-en-rAU
rm -rf ./frameworks/base/packages/PrintSpooler/res/values-en-rAU
rm -rf ./frameworks/base/packages/SettingsLib/res/values-en-rAU
rm -rf ./frameworks/base/packages/CaptivePortalLogin/res/values-en-rAU
rm -rf ./frameworks/base/packages/Keyguard/res/values-en-rAU
rm -rf ./frameworks/base/packages/DefaultContainerService/res/values-en-rAU
rm -rf ./frameworks/base/packages/InputDevices/res/values-en-rAU
rm -rf ./frameworks/base/packages/Shell/res/values-en-rAU
rm -rf ./frameworks/base/packages/BackupRestoreConfirmation/res/values-en-rAU
rm -rf ./frameworks/base/packages/FusedLocation/res/values-en-rAU
rm -rf ./packages/apps/Contacts/res/values-en-rAU
rm -rf ./packages/apps/DeskClock/res/values-en-rAU
rm -rf ./packages/apps/Music/res/values-en-rAU
rm -rf ./packages/apps/Settings/tests/app/res/values-en-rAU
rm -rf ./packages/apps/Settings/res/values-en-rAU
rm -rf ./packages/apps/WallpaperPicker/res/values-en-rAU
rm -rf ./packages/apps/Gallery2/res/values-en-rAU
rm -rf ./packages/apps/BasicSmsReceiver/res/values-en-rAU
rm -rf ./packages/apps/Dialer/InCallUI/res/values-en-rAU
rm -rf ./packages/apps/Dialer/res/values-en-rAU
rm -rf ./packages/apps/ExactCalculator/res/values-en-rAU
rm -rf ./packages/apps/EmergencyInfo/res/values-en-rAU
rm -rf ./packages/apps/PackageInstaller/res/values-en-rAU
rm -rf ./packages/apps/Calendar/res/values-en-rAU
rm -rf ./packages/apps/Bluetooth/res/values-en-rAU
rm -rf ./packages/apps/Messaging/res/values-en-rAU
rm -rf ./packages/apps/Nfc/res/values-en-rAU
rm -rf ./packages/apps/Launcher2/res/values-en-rAU
rm -rf ./packages/apps/CellBroadcastReceiver/tests/res/values-en-rAU
rm -rf ./packages/apps/CellBroadcastReceiver/res/values-en-rAU
rm -rf ./packages/apps/PhoneCommon/res/values-en-rAU
rm -rf ./packages/apps/Launcher3/WallpaperPicker/res/values-en-rAU
rm -rf ./packages/apps/Launcher3/res/values-en-rAU
rm -rf ./packages/apps/SoundRecorder/res/values-en-rAU
rm -rf ./packages/apps/MusicFX/res/values-en-rAU
rm -rf ./packages/apps/Camera2/res/values-en-rAU
rm -rf ./packages/apps/Calculator/res/values-en-rAU
rm -rf ./packages/apps/ManagedProvisioning/res/values-en-rAU
rm -rf ./packages/apps/CertInstaller/res/values-en-rAU
rm -rf ./packages/apps/TvSettings/Settings/res/values-en-rAU
rm -rf ./packages/apps/Email/res/values-en-rAU
rm -rf ./packages/apps/Email/UnifiedEmail/res/values-en-rAU
rm -rf ./packages/apps/KeyChain/res/values-en-rAU
rm -rf ./packages/apps/Stk/res/values-en-rAU
rm -rf ./packages/apps/Tag/res/values-en-rAU
rm -rf ./packages/apps/Gallery/res/values-en-rAU
rm -rf ./packages/apps/ContactsCommon/res/values-en-rAU
rm -rf ./packages/inputmethods/LatinIME/java/res/values-en-rAU
rm -rf ./packages/services/Telecomm/res/values-en-rAU
rm -rf ./packages/services/Telephony/res/values-en-rAU
rm -rf ./packages/services/Telephony/sip/res/values-en-rAU
rm -rf ./packages/screensavers/PhotoTable/res/values-en-rAU
rm -rf ./packages/screensavers/Basic/res/values-en-rAU
rm -rf ./packages/wallpapers/LivePicker/res/values-en-rAU
rm -rf ./packages/providers/ContactsProvider/res/values-en-rAU
rm -rf ./packages/providers/MediaProvider/res/values-en-rAU
rm -rf ./packages/providers/UserDictionaryProvider/res/values-en-rAU
rm -rf ./packages/providers/TelephonyProvider/res/values-en-rAU
rm -rf ./packages/providers/BlockedNumberProvider/res/values-en-rAU
rm -rf ./packages/providers/TvProvider/res/values-en-rAU
rm -rf ./packages/providers/DownloadProvider/res/values-en-rAU
rm -rf ./packages/providers/DownloadProvider/ui/res/values-en-rAU
rm -rf ./packages/providers/CalendarProvider/res/values-en-rAU
# rm values-en-rIN
rm -rf ./vendor/mediatek/proprietary/packages/apps/Browser/res/values-en-rIN
rm -rf ./vendor/mediatek/proprietary/packages/apps/HotKnotConnectivity/res/values-en-rIN
rm -rf ./vendor/mediatek/proprietary/packages/apps/Calendar/res/values-en-rIN
rm -rf ./vendor/mediatek/proprietary/packages/apps/FMRadio/res/values-en-rIN
rm -rf ./vendor/mediatek/proprietary/packages/apps/HotKnotBeam/res/values-en-rIN
rm -rf ./vendor/mediatek/proprietary/packages/apps/Exchange/res/values-en-rIN
rm -rf ./vendor/mediatek/proprietary/packages/apps/Mms/res/values-en-rIN
rm -rf ./frameworks/opt/chips/res/values-en-rIN
rm -rf ./frameworks/opt/chips/sample/res/values-en-rIN
rm -rf ./frameworks/opt/colorpicker/res/values-en-rIN
rm -rf ./frameworks/opt/timezonepicker/res/values-en-rIN
rm -rf ./frameworks/opt/setupwizard/library/main/res/values-en-rIN
rm -rf ./frameworks/opt/setupwizard/navigationbar/res/values-en-rIN
rm -rf ./frameworks/opt/datetimepicker/res/values-en-rIN
rm -rf ./frameworks/opt/photoviewer/res/values-en-rIN
rm -rf ./frameworks/opt/photoviewer/sample/res/values-en-rIN
rm -rf ./frameworks/base/core/res/res/values-en-rIN
rm -rf ./frameworks/base/packages/SettingsProvider/res/values-en-rIN
rm -rf ./frameworks/base/packages/VpnDialogs/res/values-en-rIN
rm -rf ./frameworks/base/packages/ExternalStorageProvider/res/values-en-rIN
rm -rf ./frameworks/base/packages/SystemUI/res/values-en-rIN
rm -rf ./frameworks/base/packages/WallpaperCropper/res/values-en-rIN
rm -rf ./frameworks/base/packages/DocumentsUI/res/values-en-rIN
rm -rf ./frameworks/base/packages/PrintSpooler/res/values-en-rIN
rm -rf ./frameworks/base/packages/SettingsLib/res/values-en-rIN
rm -rf ./frameworks/base/packages/CaptivePortalLogin/res/values-en-rIN
rm -rf ./frameworks/base/packages/Keyguard/res/values-en-rIN
rm -rf ./frameworks/base/packages/DefaultContainerService/res/values-en-rIN
rm -rf ./frameworks/base/packages/InputDevices/res/values-en-rIN
rm -rf ./frameworks/base/packages/Shell/res/values-en-rIN
rm -rf ./frameworks/base/packages/BackupRestoreConfirmation/res/values-en-rIN
rm -rf ./frameworks/base/packages/FusedLocation/res/values-en-rIN
rm -rf ./frameworks/ex/chips/res/values-en-rIN
rm -rf ./packages/apps/Contacts/res/values-en-rIN
rm -rf ./packages/apps/DeskClock/res/values-en-rIN
rm -rf ./packages/apps/Music/res/values-en-rIN
rm -rf ./packages/apps/Settings/tests/app/res/values-en-rIN
rm -rf ./packages/apps/Settings/res/values-en-rIN
rm -rf ./packages/apps/WallpaperPicker/res/values-en-rIN
rm -rf ./packages/apps/Gallery2/res/values-en-rIN
rm -rf ./packages/apps/BasicSmsReceiver/res/values-en-rIN
rm -rf ./packages/apps/Dialer/InCallUI/res/values-en-rIN
rm -rf ./packages/apps/Dialer/res/values-en-rIN
rm -rf ./packages/apps/ExactCalculator/res/values-en-rIN
rm -rf ./packages/apps/EmergencyInfo/res/values-en-rIN
rm -rf ./packages/apps/PackageInstaller/res/values-en-rIN
rm -rf ./packages/apps/Calendar/res/values-en-rIN
rm -rf ./packages/apps/Bluetooth/res/values-en-rIN
rm -rf ./packages/apps/Messaging/res/values-en-rIN
rm -rf ./packages/apps/Nfc/res/values-en-rIN
rm -rf ./packages/apps/HTMLViewer/res/values-en-rIN
rm -rf ./packages/apps/Launcher2/res/values-en-rIN
rm -rf ./packages/apps/CellBroadcastReceiver/tests/res/values-en-rIN
rm -rf ./packages/apps/CellBroadcastReceiver/res/values-en-rIN
rm -rf ./packages/apps/PhoneCommon/res/values-en-rIN
rm -rf ./packages/apps/Launcher3/WallpaperPicker/res/values-en-rIN
rm -rf ./packages/apps/Launcher3/res/values-en-rIN
rm -rf ./packages/apps/SoundRecorder/res/values-en-rIN
rm -rf ./packages/apps/MusicFX/res/values-en-rIN
rm -rf ./packages/apps/Camera2/res/values-en-rIN
rm -rf ./packages/apps/Calculator/res/values-en-rIN
rm -rf ./packages/apps/ManagedProvisioning/res/values-en-rIN
rm -rf ./packages/apps/CertInstaller/res/values-en-rIN
rm -rf ./packages/apps/TvSettings/Settings/res/values-en-rIN
rm -rf ./packages/apps/Email/res/values-en-rIN
rm -rf ./packages/apps/Email/UnifiedEmail/res/values-en-rIN
rm -rf ./packages/apps/KeyChain/res/values-en-rIN
rm -rf ./packages/apps/Stk/res/values-en-rIN
rm -rf ./packages/apps/Tag/res/values-en-rIN
rm -rf ./packages/apps/Protips/res/values-en-rIN
rm -rf ./packages/apps/Gallery/res/values-en-rIN
rm -rf ./packages/apps/ContactsCommon/res/values-en-rIN
rm -rf ./packages/inputmethods/LatinIME/java/res/values-en-rIN
rm -rf ./packages/services/Telecomm/res/values-en-rIN
rm -rf ./packages/services/Telecomm/res_ext/values-en-rIN
rm -rf ./packages/services/Telephony/res/values-en-rIN
rm -rf ./packages/services/Telephony/sip/res/values-en-rIN
rm -rf ./packages/screensavers/PhotoTable/res/values-en-rIN
rm -rf ./packages/screensavers/Basic/res/values-en-rIN
rm -rf ./packages/wallpapers/LivePicker/res/values-en-rIN
rm -rf ./packages/providers/ContactsProvider/res/values-en-rIN
rm -rf ./packages/providers/MediaProvider/res/values-en-rIN
rm -rf ./packages/providers/UserDictionaryProvider/res/values-en-rIN
rm -rf ./packages/providers/TelephonyProvider/res/values-en-rIN
rm -rf ./packages/providers/BlockedNumberProvider/res/values-en-rIN
rm -rf ./packages/providers/TvProvider/res/values-en-rIN
rm -rf ./packages/providers/DownloadProvider/res/values-en-rIN
rm -rf ./packages/providers/DownloadProvider/ui/res/values-en-rIN
rm -rf ./packages/providers/ApplicationsProvider/res/values-en-rIN
rm -rf ./packages/providers/CalendarProvider/res/values-en-rIN
# rm values-en-rNZ
rm -rf ./vendor/mediatek/proprietary/packages/apps/Browser/res/values-en-rNZ
rm -rf ./frameworks/base/core/res/res/values-en-rNZ
# rm values-en-rSG
rm -rf ./vendor/mediatek/proprietary/packages/apps/Browser/res/values-en-rSG
rm -rf ./frameworks/base/core/res/res/values-en-rSG
# rm values-en-rZA
rm -rf ./vendor/mediatek/proprietary/packages/apps/Browser/res/values-en-rZA
rm -rf ./frameworks/base/core/res/res/values-en-rZA
# rm values-en-rUS
rm -rf ./packages/providers/DownloadProvider/res/values-en-rUS
rm -rf ./frameworks/base/packages/DocumentsUI/res/values-en-rUS
